
development:
  adapter: postgresql
  database: subcontrax
  host: localhost
  username: "mark"
  password: "nuni2003"

test:
  adapter: postgresql
  host: localhost
  database: subcontrax
  username: "mark"
  password: "nuni2003"
