
development:
  adapter: postgresql
  database: subcontrax-dev
  host: localhost
  username: "PLEASE PUT USER NAME HERE"
  password: "PASSWORD GOES HERE"

test: &test
  adapter: postgresql
  host: localhost
  database: subcontrax-test
  username: "PLEASE PUT USER NAME HERE"
  password: "PASSWORD GOES HERE"

cucumber:
  <<: *test