
development:
  adapter: postgresql
  database: subcontrax-dev
  host: localhost
  username: "mark"
  password: "nuni2003"

test: &test
  adapter: postgresql
  host: localhost
  database: subcontrax-test
  username: "mark"
  password: "nuni2003"

cucumber:
  <<: *test