
development:
  adapter: postgresql
  database: subcontrax-dev
  host: localhost
  username: "postgres"
  password: "Maxim2012"

test: &test
  adapter: postgresql
  host: localhost
  database: subcontrax-test
  username: "postgres"
  password: "Maxim2012"

cucumber:
  <<: *test